//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleXmlFiel.ServiceReferencePrueba {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", ConfigurationName="ServiceReferencePrueba.TitulosPortType")]
    public interface TitulosPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación cargaTituloElectronico no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse1 cargaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse1> cargaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaProcesoTituloElectronico no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse1 consultaProcesoTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse1> consultaProcesoTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación descargaTituloElectronico no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse1 descargaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse1> descargaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación cancelaTituloElectronico no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse1 cancelaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse1> cancelaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cargaTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreArchivoField;
        
        private byte[] archivoBase64Field;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
                this.RaisePropertyChanged("nombreArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] archivoBase64 {
            get {
                return this.archivoBase64Field;
            }
            set {
                this.archivoBase64Field = value;
                this.RaisePropertyChanged("archivoBase64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class autenticacionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cargaTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargaTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest cargaTituloElectronicoRequest;
        
        public cargaTituloElectronicoRequest1() {
        }
        
        public cargaTituloElectronicoRequest1(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest cargaTituloElectronicoRequest) {
            this.cargaTituloElectronicoRequest = cargaTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargaTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse cargaTituloElectronicoResponse;
        
        public cargaTituloElectronicoResponse1() {
        }
        
        public cargaTituloElectronicoResponse1(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse cargaTituloElectronicoResponse) {
            this.cargaTituloElectronicoResponse = cargaTituloElectronicoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class consultaProcesoTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class consultaProcesoTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private short estatusLoteField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short estatusLote {
            get {
                return this.estatusLoteField;
            }
            set {
                this.estatusLoteField = value;
                this.RaisePropertyChanged("estatusLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProcesoTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest;
        
        public consultaProcesoTituloElectronicoRequest1() {
        }
        
        public consultaProcesoTituloElectronicoRequest1(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest) {
            this.consultaProcesoTituloElectronicoRequest = consultaProcesoTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaProcesoTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse consultaProcesoTituloElectronicoResponse;
        
        public consultaProcesoTituloElectronicoResponse1() {
        }
        
        public consultaProcesoTituloElectronicoResponse1(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse consultaProcesoTituloElectronicoResponse) {
            this.consultaProcesoTituloElectronicoResponse = consultaProcesoTituloElectronicoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class descargaTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class descargaTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private string mensajeField;
        
        private byte[] titulosBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] titulosBase64 {
            get {
                return this.titulosBase64Field;
            }
            set {
                this.titulosBase64Field = value;
                this.RaisePropertyChanged("titulosBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest descargaTituloElectronicoRequest;
        
        public descargaTituloElectronicoRequest1() {
        }
        
        public descargaTituloElectronicoRequest1(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest descargaTituloElectronicoRequest) {
            this.descargaTituloElectronicoRequest = descargaTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse descargaTituloElectronicoResponse;
        
        public descargaTituloElectronicoResponse1() {
        }
        
        public descargaTituloElectronicoResponse1(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse descargaTituloElectronicoResponse) {
            this.descargaTituloElectronicoResponse = descargaTituloElectronicoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cancelaTituloElectronicoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string folioControlField;
        
        private string motCancelacionField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string folioControl {
            get {
                return this.folioControlField;
            }
            set {
                this.folioControlField = value;
                this.RaisePropertyChanged("folioControl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string motCancelacion {
            get {
                return this.motCancelacionField;
            }
            set {
                this.motCancelacionField = value;
                this.RaisePropertyChanged("motCancelacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cancelaTituloElectronicoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelaTituloElectronicoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest;
        
        public cancelaTituloElectronicoRequest1() {
        }
        
        public cancelaTituloElectronicoRequest1(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest) {
            this.cancelaTituloElectronicoRequest = cancelaTituloElectronicoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelaTituloElectronicoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse cancelaTituloElectronicoResponse;
        
        public cancelaTituloElectronicoResponse1() {
        }
        
        public cancelaTituloElectronicoResponse1(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse cancelaTituloElectronicoResponse) {
            this.cancelaTituloElectronicoResponse = cancelaTituloElectronicoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TitulosPortTypeChannel : ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TitulosPortTypeClient : System.ServiceModel.ClientBase<ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType>, ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType {
        
        public TitulosPortTypeClient() {
        }
        
        public TitulosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TitulosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitulosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitulosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse1 ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.cargaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1 request) {
            return base.Channel.cargaTituloElectronico(request);
        }
        
        public ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse cargaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest cargaTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1();
            inValue.cargaTituloElectronicoRequest = cargaTituloElectronicoRequest;
            ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse1 retVal = ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).cargaTituloElectronico(inValue);
            return retVal.cargaTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse1> ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.cargaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1 request) {
            return base.Channel.cargaTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoResponse1> cargaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest cargaTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.cargaTituloElectronicoRequest1();
            inValue.cargaTituloElectronicoRequest = cargaTituloElectronicoRequest;
            return ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).cargaTituloElectronicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse1 ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.consultaProcesoTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1 request) {
            return base.Channel.consultaProcesoTituloElectronico(request);
        }
        
        public ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse consultaProcesoTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1();
            inValue.consultaProcesoTituloElectronicoRequest = consultaProcesoTituloElectronicoRequest;
            ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse1 retVal = ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).consultaProcesoTituloElectronico(inValue);
            return retVal.consultaProcesoTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse1> ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.consultaProcesoTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1 request) {
            return base.Channel.consultaProcesoTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoResponse1> consultaProcesoTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest consultaProcesoTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.consultaProcesoTituloElectronicoRequest1();
            inValue.consultaProcesoTituloElectronicoRequest = consultaProcesoTituloElectronicoRequest;
            return ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).consultaProcesoTituloElectronicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse1 ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.descargaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1 request) {
            return base.Channel.descargaTituloElectronico(request);
        }
        
        public ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse descargaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest descargaTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1();
            inValue.descargaTituloElectronicoRequest = descargaTituloElectronicoRequest;
            ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse1 retVal = ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).descargaTituloElectronico(inValue);
            return retVal.descargaTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse1> ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.descargaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1 request) {
            return base.Channel.descargaTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoResponse1> descargaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest descargaTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.descargaTituloElectronicoRequest1();
            inValue.descargaTituloElectronicoRequest = descargaTituloElectronicoRequest;
            return ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).descargaTituloElectronicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse1 ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.cancelaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1 request) {
            return base.Channel.cancelaTituloElectronico(request);
        }
        
        public ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse cancelaTituloElectronico(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1();
            inValue.cancelaTituloElectronicoRequest = cancelaTituloElectronicoRequest;
            ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse1 retVal = ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).cancelaTituloElectronico(inValue);
            return retVal.cancelaTituloElectronicoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse1> ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType.cancelaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1 request) {
            return base.Channel.cancelaTituloElectronicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoResponse1> cancelaTituloElectronicoAsync(ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest cancelaTituloElectronicoRequest) {
            ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1 inValue = new ConsoleXmlFiel.ServiceReferencePrueba.cancelaTituloElectronicoRequest1();
            inValue.cancelaTituloElectronicoRequest = cancelaTituloElectronicoRequest;
            return ((ConsoleXmlFiel.ServiceReferencePrueba.TitulosPortType)(this)).cancelaTituloElectronicoAsync(inValue);
        }
    }
}
